# Generated by Django 5.0.6 on 2024-07-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cliente_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Empresa',
        ),
    ]
